[[crates]]
name = "dyon"
source = "crates"

[[crates]]
name = 'gluon'
source = "crates"

[[crates]]
name = 'rhai'
source = "crates"

[[crates]]
name = "ketos"
source = "crates"

[[crates]]
name = 'hlua'
source = "crates"

[[crates]]
name = 'rlua'
source = "crates"

[[crates]]
name = 'lichen'
source = "crates"
