[[crates]]
name = "rust-openvr/rust-openvr"
source = "github"

[[crates]]
name = 'rust-webvr'
source = "crates"

[[crates]]
name = 'openvr'
source = "crates"

[[crates]]
name = "rovr"
source = "crates"

[[crates]]
name = 'libovr'
source = "crates"
