[[crates]]
name = "amethyst"
source = "crates"
[[crates]]
name = 'piston'
source = "crates"
[[crates]]
name = 'corange-rs'
source = "crates"
[[crates]]
name = 'ggez'
source = "crates"
[[crates]]
name = 'darkengine'
source = "crates"
[[crates]]
name = 'turbine'
source = "crates"
[[crates]]
name = 'caper'
source = "crates"
[[crates]]
name = 'mold2d'
source = "crates"
[[crates]]
name = 'nitro'
source = "crates"
[[crates]]
name = 'sdl2'
source = "crates"
[[crates]]
name = 'godot'
source = "crates"

[[crates]]
name = "ChariotEngine/Chariot"
source = "github"
[[crates]]
name = "Siebencorgie/jakar-engine"
source = "github"
[[crates]]
name = "Gigoteur/UnicornConsole"
source = "github"